# Generated by Django 3.1.4 on 2021-05-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10000)),
                ('last_name', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=254)),
                ('reviewers', models.ManyToManyField(related_name='_employee_reviewers_+', to='paypayapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReviewSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(to='paypayapp.Answer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_employee_submission', to='paypayapp.employee')),
                ('performance_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypayapp.performancereview')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypayapp.employee')),
            ],
        ),
        migrations.AddField(
            model_name='performancereview',
            name='questions',
            field=models.ManyToManyField(to='paypayapp.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypayapp.rating'),
        ),
    ]
